# Generated by Django 2.2.3 on 2019-07-30 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(0, 'Baño'), (1, 'Cocina'), (2, 'Comedor'), (3, 'Recamara')], default=0, max_length=1),
        ),
    ]
