# Generated by Django 2.2.3 on 2019-07-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(0, 'Baño'), (1, 'Cocina'), (2, 'Comedor'), (3, 'Recamara'), (4, 'Sala')], default=0, max_length=1),
        ),
    ]
