# Generated by Django 2.2.3 on 2019-07-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190730_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Baño', 'Baño'), ('Cocina', 'Cocina'), ('Comedor', 'Comedor'), ('Recamara', 'Recamara'), ('Sala', 'Sala')], default='Baño', max_length=10),
        ),
    ]
